### ISSUE TITLE
Does not work properly on iOS8 beta 

### ISSUE THREAD

**Issue by Goro-Otsubo** [mrcrow/MRFlipTransition#1]
Looks like screen goes black at the end of dismissing.

**Comment by mrcrow** [comment]
Thanks @Goro-Otsubo ,I got the same black screen on iOS 8 simulator, trying to figure it out.

**Comment by mrcrow** [comment]
@Goro-Otsubo , this issue is reported as a bug on iOS 8
Referred to the [solution](http://stackoverflow.com/questions/24338700/from-view-controller-disappears-using-uiviewcontrollercontexttransitioning) on stackoverflow, I updated the codes. 
You can test it again

**Comment by Goro-Otsubo** [comment]
It works great! Thanks.
